name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v3
      -
        name: 'Use Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      -
        name: 'Install Package'
        run: 'npm install --global stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
        run: 'stargazed --username  "rafael-neri" --token ${GITHUB_TOKEN} --repo "awesome-stars" --message "stargazed update by GitHub Actions Workflow" --sort'
